---
abstract: 'Dist::Zilla according to wolverian'
author:
  - 'Ilmari Vacklin <ilmari.vacklin@cs.helsinki.fi>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-WOLVERIAN
requires:
  Dist::Zilla::Plugin::AutoPrereqs: 0
  Dist::Zilla::Plugin::Bugtracker: 0
  Dist::Zilla::Plugin::EOLTests: 0
  Dist::Zilla::Plugin::Git: 0
  Dist::Zilla::Plugin::InstallGuide: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaTests: 0
  Dist::Zilla::Plugin::MinimumPerl: 0
  Dist::Zilla::Plugin::MinimumVersionTests: 0
  Dist::Zilla::Plugin::ModuleBuild: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::Repository: 0
  MooseX::Declare: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-WOLVERIAN
  homepage: http://github.com/wolverian/Dist-Zilla-PluginBundle-WOLVERIAN/tree
  repository: git://github.com/wolverian/Dist-Zilla-PluginBundle-WOLVERIAN.git
version: v0.0.7
